# Switch to 'postgresql' in config/database.yml before running 'docker-compose up'
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/sample_rails_application
      - /sample_rails_application/node_modules
    ports:
      - "3000:3000"
      # Ports required for debugging
      - "1234:1234"
      - "26166:26168"
    depends_on:
      - db